In [11]:
import pandas as pd

# CSV 파일을 데이터프레임으로 불러오기
data = pd.read_csv("2020_환경_통합.csv",encoding="euc-kr")
data= data.drop(columns= ["온도_외부","풍속_외부","풍향_외부","누적일사량_외부","강우감지",'일사량_외부','잔존CO2','토양온도'])
data = data[data["품목"]== "딸기"]
# 데이터 확인 (첫 몇 줄 출력)
data

          도  시군  품목  작기  농가명              측정시간  온도_내부  상대습도_내부
239446   경남  거창  딸기   1   51  2020-09-12 00:00   19.8     99.9
239447   경남  거창  딸기   1   51  2020-09-12 01:00   19.4     99.2
239448   경남  거창  딸기   1   51  2020-09-12 02:00   19.5     99.3
239449   경남  거창  딸기   1   51  2020-09-12 03:00   19.0     99.7
239450   경남  거창  딸기   1   51  2020-09-12 04:00   18.6     99.9
...      ..  ..  ..  ..  ...               ...    ...      ...
1055819  충북  청주  딸기   1    1  2021-04-23 20:00   17.2     46.4
1055820  충북  청주  딸기   1    1  2021-04-23 21:00   17.2     42.6
1055821  충북  청주  딸기   1    1  2021-04-23 22:00   16.6     44.2
1055822  충북  청주  딸기   1    1  2021-04-23 23:00   16.1     44.4
1055823  충북  청주  딸기   1    1  2021-04-23 23:55   15.6     46.3

[270743 rows x 8 columns]

In [13]:
data.to_csv("2020딸기내부환경.csv",index=False)

In [23]:
import pandas as pd

# CSV 파일을 데이터프레임으로 불러오기
data = pd.read_csv("딸기_2020_생육_통합.csv",encoding="euc-kr")
data['화방별착과수'] = data['화방별착과수'].fillna(0)
data= data.drop(columns= ["화방번호","액아구분"])
data

,도,시군,품목,작기,농가명,조사일자,개체번호,초장,엽수,엽장,엽폭,엽병장,관부직경,화방별착과수
0,경남,거창,딸기,1,51,2020-10-08,1,24.0,4.0,6.5,4.6,16.0,13.22,0.0
1,경남,거창,딸기,1,51,2020-10-08,2,22.8,5.0,7.5,5.3,9.0,12.41,0.0
2,경남,거창,딸기,1,51,2020-10-08,3,25.5,5.0,7.4,5.6,8.6,14.42,0.0
3,경남,거창,딸기,1,51,2020-10-08,4,30.0,5.0,9.6,6.3,13.7,15.73,0.0
4,경남,거창,딸기,1,51,2020-10-15,1,24.0,5.0,10.4,6.7,8.7,12.27,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17587,충북,청주,딸기,1,1,2021-05-25,4,23.0,24.0,11.7,10.2,7.2,15.88,0.0
17588,충북,청주,딸기,1,1,2021-05-25,4,NaN,NaN,NaN,NaN,NaN,NaN,0.0
17589,충북,청주,딸기,1,1,2021-05-25,4,NaN,NaN,NaN,NaN,NaN,NaN,0.0
17590,충북,청주,딸기,1,1,2021-05-25,4,NaN,NaN,NaN,NaN,NaN,NaN,0.0
17591,충북,청주,딸기,1,1,2021-05-25,4,NaN,NaN,NaN,NaN,NaN,NaN,6.0

In [25]:
columns_to_fill = ['초장', '엽수', '엽장', '엽폭', '엽병장', '관부직경']

# 농가명, 조사일자, 개체번호로 그룹화하여 결측값을 채움
for col in columns_to_fill:
    data[col] = data.groupby(['농가명', '조사일자', '개체번호'])[col].transform(lambda x: x.fillna(x.mean()))

# 결과 확인
data

,도,시군,품목,작기,농가명,조사일자,개체번호,초장,엽수,엽장,엽폭,엽병장,관부직경,화방별착과수
0,경남,거창,딸기,1,51,2020-10-08,1,24.0,4.0,6.50,4.6,16.0,13.220,0.0
1,경남,거창,딸기,1,51,2020-10-08,2,22.8,5.0,7.50,5.3,9.0,12.410,0.0
2,경남,거창,딸기,1,51,2020-10-08,3,25.5,5.0,7.40,5.6,8.6,14.420,0.0
3,경남,거창,딸기,1,51,2020-10-08,4,30.0,5.0,9.60,6.3,13.7,15.730,0.0
4,경남,거창,딸기,1,51,2020-10-15,1,24.0,5.0,10.40,6.7,8.7,12.270,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17587,충북,청주,딸기,1,1,2021-05-25,4,23.0,24.0,11.70,10.2,7.2,15.880,0.0
17588,충북,청주,딸기,1,1,2021-05-25,4,30.0,22.5,14.95,8.4,13.1,15.555,0.0
17589,충북,청주,딸기,1,1,2021-05-25,4,30.0,22.5,14.95,8.4,13.1,15.555,0.0
17590,충북,청주,딸기,1,1,2021-05-25,4,30.0,22.5,14.95,8.4,13.1,15.555,0.0
17591,충북,청주,딸기,1,1,2021-05-25,4,30.0,22.5,14.95,8.4,13.1,15.555,6.0

In [27]:
data.to_csv("2020딸기생육.csv",index=False)

In [33]:
import pandas as pd

# CSV 파일을 데이터프레임으로 불러오기
data = pd.read_csv("2020_판매_통합.csv",encoding="euc-kr")
data = data[data["품목"]== "딸기"]
data= data.drop(columns= ["판매금액"])
data

        도  시군  품목  작기  농가명        출하일자  총출하량
8375   경남  거창  딸기   1   51  2020-11-16   2.0
8376   경남  거창  딸기   1   51  2020-11-16   2.0
8377   경남  거창  딸기   1   51  2020-11-16   8.0
8378   경남  거창  딸기   1   51  2020-11-16   2.0
8379   경남  거창  딸기   1   51  2020-11-18   2.0
...    ..  ..  ..  ..  ...         ...   ...
38574  충북  청주  딸기   1    1  2021-05-25  11.0
38575  충북  청주  딸기   1    1  2021-05-26  12.0
38576  충북  청주  딸기   1    1  2021-05-27  13.0
38577  충북  청주  딸기   1    1  2021-05-28  15.0
38578  충북  청주  딸기   1    1  2021-05-31  17.0

[14689 rows x 7 columns]

In [35]:
data.to_csv("2020딸기판매.csv",index=False)