In [71]:
import pandas as pd

# CSV 파일 읽기
file1 = pd.read_csv('2018딸기생육전처리.csv', encoding='utf-8')
file2 = pd.read_csv('2018딸기재배월평균.csv', encoding='utf-8')

file1

,도,시군,품목,작기,농가명,조사일자,개체번호,액아구분,초장,엽수,엽장,엽폭,엽병장,관부직경,화방번호,화방별착과수
0,경남,거창,딸기,1,58,2018-10-16,1,본주,26.2,4.0,11.4,8.2,13.6,13.46,0.0,0.0
1,경남,거창,딸기,1,58,2018-10-16,2,본주,25.2,4.0,10.3,7.3,14.8,12.02,0.0,0.0
2,경남,거창,딸기,1,58,2018-10-16,3,본주,24.5,3.0,10.0,7.0,14.3,12.00,0.0,0.0
3,경남,거창,딸기,1,58,2018-10-16,4,본주,30.3,4.0,10.0,7.4,17.5,12.66,0.0,0.0
4,경남,거창,딸기,1,58,2018-10-26,1,본주,27.6,4.0,12.0,8.2,12.3,15.15,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16648,충북,청주,딸기,1,1,2019-05-17,2,본주,23.0,27.0,8.5,6.0,13.0,19.00,8.0,2.0
16649,충북,청주,딸기,1,1,2019-05-17,3,본주,22.5,12.0,9.1,5.3,12.7,17.33,10.0,0.0
16650,충북,청주,딸기,1,1,2019-05-17,3,본주,22.5,12.0,9.1,5.3,12.7,17.33,8.0,2.0
16651,충북,청주,딸기,1,1,2019-05-17,3,본주,22.5,12.0,9.1,5.3,12.7,17.33,9.0,5.0
16652,충북,청주,딸기,1,1,2019-05-17,4,본주,23.0,24.0,7.5,5.5,11.5,16.60,6.0,2.0

In [73]:
file2

       농가명          날짜   작기  온도_내부  상대습도_내부
0        1  2018-11-05  1.0  22.34    81.60
1        1  2018-11-06  1.0  19.38    85.14
2        1  2018-11-07  1.0  16.94    98.76
3        1  2018-11-08  1.0  16.73    99.90
4        1  2018-11-12  1.0  18.67    81.52
...    ...         ...  ...    ...      ...
13961    9  2019-05-08  1.0  19.04    70.00
13962    9  2019-05-09  1.0  20.65    69.12
13963    9  2019-05-10  1.0  20.48    67.83
13964    9  2019-05-11  1.0  21.47    71.38
13965    9  2019-05-12  1.0  21.48    71.16

[13966 rows x 5 columns]

In [75]:
# 날짜 형식 변환
file1['조사일자'] = pd.to_datetime(file1['조사일자'], format='%Y-%m-%d')
file2['날짜'] = pd.to_datetime(file2['날짜'], format='%Y-%m-%d')

In [83]:
# 두 데이터 병합
merged_data = pd.merge(file1, file2, left_on=['농가명', '조사일자'], right_on=['농가명', '날짜'], how='left')

# 병합 후 필요 없는 '날짜' 컬럼 삭제
merged_data = merged_data.drop(columns=['날짜'])

# 병합된 데이터 확인
df = merged_data
df

,도,시군,품목,작기_x,농가명,조사일자,개체번호,액아구분,초장,엽수,엽장,엽폭,엽병장,관부직경,화방번호,화방별착과수,작기_y,온도_내부,상대습도_내부
0,경남,거창,딸기,1,58,2018-10-16,1,본주,26.2,4.0,11.4,8.2,13.6,13.46,0.0,0.0,1.0,16.24,99.35
1,경남,거창,딸기,1,58,2018-10-16,2,본주,25.2,4.0,10.3,7.3,14.8,12.02,0.0,0.0,1.0,16.24,99.35
2,경남,거창,딸기,1,58,2018-10-16,3,본주,24.5,3.0,10.0,7.0,14.3,12.00,0.0,0.0,1.0,16.24,99.35
3,경남,거창,딸기,1,58,2018-10-16,4,본주,30.3,4.0,10.0,7.4,17.5,12.66,0.0,0.0,1.0,16.24,99.35
4,경남,거창,딸기,1,58,2018-10-26,1,본주,27.6,4.0,12.0,8.2,12.3,15.15,1.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16648,충북,청주,딸기,1,1,2019-05-17,2,본주,23.0,27.0,8.5,6.0,13.0,19.00,8.0,2.0,NaN,NaN,NaN
16649,충북,청주,딸기,1,1,2019-05-17,3,본주,22.5,12.0,9.1,5.3,12.7,17.33,10.0,0.0,NaN,NaN,NaN
16650,충북,청주,딸기,1,1,2019-05-17,3,본주,22.5,12.0,9.1,5.3,12.7,17.33,8.0,2.0,NaN,NaN,NaN
16651,충북,청주,딸기,1,1,2019-05-17,3,본주,22.5,12.0,9.1,5.3,12.7,17.33,9.0,5.0,NaN,NaN,NaN
16652,충북,청주,딸기,1,1,2019-05-17,4,본주,23.0,24.0,7.5,5.5,11.5,16.60,6.0,2.0,NaN,NaN,NaN

In [85]:
df=df.drop(columns=["작기_y"])

In [89]:
df=df.rename(columns={"작기_x":"작기"})

In [95]:
df.to_csv("딸기데이터병합.csv",index=False)

In [45]:
import pandas as pd

# CSV 파일 읽기
file1 = pd.read_csv('2018딸기생육전처리.csv', encoding='utf-8')
file2 = pd.read_csv('2018딸기재배환경전처리.csv', encoding='utf-8')

# 첫 번째 파일의 조사일자를 날짜 형식으로 변환
file1['조사일자'] = pd.to_datetime(file1['조사일자']).dt.date

# 두 번째 파일의 측정시간을 datetime 형식으로 변환하고 날짜 추출
file2['측정시간'] = pd.to_datetime(file2['측정시간'])
file2['측정일자'] = file2['측정시간'].dt.date

# 숫자형 데이터만 선택하되, '농가명'과 '작기'는 제외
numeric_columns = file2.select_dtypes(include=['float64', 'int64']).columns
numeric_columns = numeric_columns.drop(['농가명', '작기'])

# 두 번째 파일에서 '농가명', '작기'를 그대로 유지하고 그룹화
file2_grouped = file2.groupby(['측정일자', '농가명', '작기'])[numeric_columns].mean().round(2).reset_index()

# 첫 번째 파일에 있는 조사일자들로 두 번째 파일을 필터링
filtered_file2 = file2_grouped[file2_grouped['측정일자'].isin(file1['조사일자'])]

# 결과 확인
filtered_file2

,측정일자,농가명,작기,온도_외부,일사량_외부,누적일사량_외부,강우감지,온도_내부,상대습도_내부,잔존CO2,토양온도
66,2018-09-10,7,1,NaN,NaN,NaN,0.00,23.46,71.99,NaN,NaN
67,2018-09-10,8,1,NaN,NaN,NaN,0.00,22.47,58.57,412.35,NaN
68,2018-09-10,10,1,NaN,NaN,NaN,0.00,25.11,60.61,NaN,NaN
69,2018-09-10,12,1,NaN,NaN,NaN,0.00,20.94,NaN,NaN,NaN
70,2018-09-10,25,1,19.23,NaN,258.58,0.00,20.93,63.00,599.75,20.95
...,...,...,...,...,...,...,...,...,...,...,...
13961,2019-06-10,10,1,NaN,NaN,NaN,0.00,21.77,74.32,NaN,NaN
13962,2019-06-10,27,1,19.40,36.67,300.33,0.21,21.49,99.45,343.71,NaN
13963,2019-06-10,28,1,19.19,36.58,300.04,0.21,19.99,97.14,360.62,NaN
13964,2019-06-11,27,1,18.10,1.00,141.00,0.00,17.60,100.00,346.00,NaN
13965,2019-06-11,28,1,19.15,64.16,180.28,0.08,20.34,97.02,363.28,NaN

In [103]:
import pandas as pd

# 첫 번째 파일과 두 번째 파일 병합 (조사일자와 측정일자를 기준)
# merged_data = pd.merge(file1, filtered_file2, left_on='조사일자', right_on='측정일자', how='inner')
merged_data = pd.read_csv("딸기데이터병합.csv",encoding="utf-8")
# 필요한 열만 선택 (화방별착과수와 환경 관련 열)
columns_for_corr = ['화방별착과수','온도_내부', '상대습도_내부','초장','엽수','엽장','엽폭','엽병장','관부직경','화방번호']

# 상관관계 계산
correlation_matrix = merged_data[columns_for_corr].corr()

# 결과 확인
correlation_matrix

,화방별착과수,온도_내부,상대습도_내부,초장,엽수,엽장,엽폭,엽병장,관부직경,화방번호
화방별착과수,1.000000,-0.149147,-0.021621,-0.059731,0.203993,0.055013,0.053232,0.010185,0.034377,-0.045593
온도_내부,-0.149147,1.000000,-0.265760,0.122912,0.199055,-0.058524,-0.062295,0.068735,0.096072,0.363735
상대습도_내부,-0.021621,-0.265760,1.000000,0.051119,-0.149625,0.066970,0.031205,-0.023304,0.044092,-0.091302
초장,-0.059731,0.122912,0.051119,1.000000,0.144993,0.266581,0.204155,0.615813,0.246161,0.186116
엽수,0.203993,0.199055,-0.149625,0.144993,1.000000,-0.171497,-0.194122,0.032355,0.227178,0.268243
엽장,0.055013,-0.058524,0.066970,0.266581,-0.171497,1.000000,0.873230,0.524632,-0.051181,-0.206783
엽폭,0.053232,-0.062295,0.031205,0.204155,-0.194122,0.873230,1.000000,0.442822,-0.025713,-0.197985
엽병장,0.010185,0.068735,-0.023304,0.615813,0.032355,0.524632,0.442822,1.000000,0.124982,0.069646
관부직경,0.034377,0.096072,0.044092,0.246161,0.227178,-0.051181,-0.025713,0.124982,1.000000,0.265606
화방번호,-0.045593,0.363735,-0.091302,0.186116,0.268243,-0.206783,-0.197985,0.069646,0.265606,1.000000

In [99]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
merged_data = merged_data.replace([np.inf, -np.inf], np.nan)
merged_data = merged_data.dropna()  # 결측값이 있는 행 제거
# 독립 변수 (환경 변수들)

X = merged_data[['온도_내부', '상대습도_내부','초장','엽수','엽장','엽폭','엽병장','관부직경','화방번호']]

# 종속 변수 (화방별착과수)
y = merged_data['화방별착과수']

# 상수항 추가
X = sm.add_constant(X)

# 다중 회귀 모델 피팅
model = sm.OLS(y, X).fit()

# 결과 출력
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 화방별착과수   R-squared:                       0.113
Model:                            OLS   Adj. R-squared:                  0.112
Method:                 Least Squares   F-statistic:                     199.3
Date:                Mon, 30 Sep 2024   Prob (F-statistic):               0.00
Time:                        12:23:03   Log-Likelihood:                -33869.
No. Observations:               14129   AIC:                         6.776e+04
Df Residuals:                   14119   BIC:                         6.783e+04
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.0004      0.249     12.059      0.000       2.513       3.488
온도_내부         -0.1674      0.008    -20.581      0.000      -0.183      -0.151
상대습도_내부       -0.0066      0.002     -3.504      0.000      -0.010      -0.003
초장            -0.0457      0.004    -12.011      0.000      -0.053      -0.038
엽수             0.0969      0.003     34.608      0.000       0.091       0.102
엽장             0.1189      0.021      5.572      0.000       0.077       0.161
엽폭             0.0662      0.025      2.639      0.008       0.017       0.115
엽병장            0.0077      0.006      1.250      0.211      -0.004       0.020
관부직경           0.0192      0.005      3.677      0.000       0.009       0.030
화방번호          -0.0320      0.012     -2.576      0.010      -0.056      -0.008
==============================================================================
Omnibus:                     5811.892   Durbin-Watson:                   1.310
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            26499.482
Skew:                           1.999   Prob(JB):                         0.00
Kurtosis:                       8.388   Cond. No.                     1.05e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""